### ISSUE TITLE
I migth be a litle incompetent

### ISSUE THREAD

**Issue by f0xon** [jahtz/easyroam-linux#1]
I jus kopie pastet the comands afer downloadng the PKCS12 file and then this ist theawnser to the second comand:
[chmod +x easyroam_nm.sh](chmod: cannot access 'easyroam_nm.sh': No such file or directory)

dos this mean someting did not properly download? or what must i do?

**Comment by jahtz** [comment]
Apologies for the confusion. It seems I mixed up some filenames when writing the documentation. The file is automatically renamed to _easyroamlinux.sh_ after downloading.

I'll correct this in the documentation shortly, but for now, please replace steps 2 and 3 with the following:
2. Make it executable:
`chmod +x easyroamlinux.sh`
3. Run setup:
`./easyroamlinux.sh`
